### ISSUE TITLE
Kerbal Voice Spam in Time Warp

### ISSUE THREAD

**Issue by FittedOrphan68** [Athlonic/Chatterer#42]
Hey I got one for ya,
For longer than I can remember now I have had an issue where if I time warp with chatterer on it begins to spam the same americans dudes voice frequently, he starts going again before hes even finished. Anyone else having this issue / have a fix? I think I may be technically using it beyond intent as I am on version 1.11.1. Don't have a log while this happens but can likely get one if needs. Other mods used is pretty extensive so I suspect it's a conflict with one of these if not a frequently seen issue. Thank you in advance for any advice, and especially the free stuff (the mod itself)!

**Comment by Beetlecat** [comment]
While I've not experienced this specifically with chatterer/time warp, I have noticed sounds getting looped/stuck with combinations of other mods that work with KSP's soundscape, such as Rocket Sounds Enhanced, or even Soundtrack Editor at times. Does it clear with a scene change (-> Tracking Station -> Flight)?

**Comment by FittedOrphan68** [comment]
Oh even that's not necessary, it stops when warp stops, i'll start poking around to see what other mods play with the sound. Now that you mention it, I recently lost engine sounds to a group (not mod specific, too easy) of engines. Thanks for your time and direction!

**Comment by Beetlecat** [comment]
Well, I'm not the mod author-- just following the project as well. You're welcome :D
